targets = [{ triple = "x86_64-unknown-linux-gnu" }, { triple = "aarch64-unknown-linux-gnu" }]

[licenses]
unlicensed = "deny"
allow = ["MIT", "Apache-2.0", "MPL-2.0"]
deny = []
copyleft = "warn"
allow-osi-fsf-free = "neither"
default = "allow"
confidence-threshold = 0.8
exceptions = []

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
allow = []
deny = []
skip = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = []
